const awsServerlessExpress = require('aws-serverless-express');
// the main.js file is generated by npm run build:iot
const app = require('./main').default;

const server = awsServerlessExpress.createServer(app);

exports.handler = (event, context) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
};
